### PR TITLE
Show map explorer

### LINKED ISSUE #99: Use GitHub pages site as map explorer
Currently, the GitHub pages site is a placeholder since we only really use it as a CDN. However, we could use the data and space to host an interactive viewer if the map. See https://github.com/Delwing/mudlet-map-reader for the main project.

### PR DESCRIPTION
**Pull request by keneanung**
This replaces the dummy website by a usable map explorer. Closes #99 

The page https://keneanung.github.io/AchaeaCrowdmap/ was built using the code. Only the default language was changed to English after the build.

### CODE REVIEW

**Comment by vadi2** [comment]
Language is still Polish for me when I load it up, can you confirm?

**Comment by keneanung** [comment]
Yeah, I did the change to the default language after I created the demo page. I'll update the demo page ASAP.

**Comment by keneanung** [comment]
Updated the demo page. You may need to use a incognito tab as the language setting is saved in the browser local storage.

**Comment by vadi2** [comment]
Looks good - how about we select some neutral area (say Delos) so people have a better first impression

**Comment by keneanung** [comment]
Done. Have another look at the demo page.

**Review by vadi2 — APPROVED** [review]
Perfect thanks :+1:

**Pull request merged**
