### PR TITLE
Updated Hashan map

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
Added new lab area, deleted old Sentinel Guild estate (it got destroyed), fixed a few rooms around the the old laboratory area, fixed planetarium

## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

### CODE REVIEW

**Comment by ryanstadther** [comment]
@vadi2, @QwindorRousseau, @TheLastDarkthorne 

I'm getting the same problem we were seeing with the last PR on this map too....whenever I change areas mudlet crashes.

**Comment by TheLastDarkthorne** [comment]
> @vadi2, @QwindorRousseau, @TheLastDarkthorne
> 
> I'm getting the same problem we were seeing with the last PR on this map too....whenever I change areas mudlet crashes.

Are you sure you are on latest mapper and mudlet version? This is odd
I have been using this version for weeks without any issues whatsoever
I will reload it tomorrow and see if something comes up

**Comment by ryanstadther** [comment]
Okay, here's my theory, if someone wants to try to recreate it. In the current map there is an area "(487) Fluvadha River, the", and that area is not in this new map. In addition, the mmp_regenerate_areas function only runs when mapping mode is enabled, which in turn resets the mmp.areatabler variable.

So, if I am on the current map, I have area 487, and when I load the new map I don't have area 487... BUT the mmp.areatabler variable does still have area 487.

Next comes into play the SVOF system, which has a people tracker, which makes labels for people on the map where it finds them. This script also has a feature where when you change areas, it clears labels.

The problem I'm seeing is that when you feed the mudlet function "getMapLabels()" with an area that doesn't exist, mudlet crashes (at least it is for me, every time).

SOO...the mmp.areatabler varable has 487, it loops through everything trying to clear the labels, and BOOM...the getMapLabels function crashes mudlet.

**Comment by ryanstadther** [comment]
if I load this map and then do MC ON and then MC OFF, it works just fine with no crashes....so I think I might be on to something...but not sure if anyone else can give it a try. Problem is I don't think we can expect everyone to do MC ON and MC OFF when they get the update.....

**Comment by vadi2** [comment]
@SlySven @Kebap does this reproduction scenario work?

**Comment by Kebap** [comment]
Sorry I don't follow along. Could you describe detailed reproduction?
Assume a new player starting Achaea for the first time. What needs to be setup for crash?
Or maybe that's all not necessary, and you can reliably crash with `getMapLabels()` and any non-existing area number?
I can try that alright, if it crashes for you like this, and you want that confirmation.

**Comment by Kebap** [comment]
https://github.com/Mudlet/Mudlet/issues/5224 seems to imply that function was indeed wonky and got fixed already. You can try with the latest development version (PTB) here: https://make.mudlet.org/snapshots/?platform=all&source=ptb 
Next Mudlet update is scheduled for May 30th.

**Comment by ryanstadther** [comment]
@Kebap no need to confirm.... @vadi2 confirmed there was an issue with getMapLabels. I tested this out on the latest development version and it works just fine.

**Comment by ryanstadther** [comment]
@TheLastDarkthorne I think it would be best if I redo the changes for area (487) "Fluvadha River, the", and we put it back in this map...even when the mudlet issue is fixed, not everyone updates right away so people still might get crashes after that. I should have time to do that later tonight.

**Comment by ryanstadther** [comment]
@TheLastDarkthorne can you load these versions up in your PR? I added back the Fluvadha River, so it should fix this crashing issue in the interim until mudlet is fixed.

[map.zip](https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/files/6505470/map.zip)

**Comment by ryanstadther** [comment]
@TheLastDarkthorne you able to update the map on this one?

**Comment by TheLastDarkthorne** [comment]
Oh sure, sorry. I will do it this weekend, having a lot of things happening

**Comment by TheLastDarkthorne** [comment]
Okidoki! I uploaded the new files, and apparently some shops got renamed in the time we were working on this so I updated them too.

**Comment by ryanstadther** [comment]
Thanks @TheLastDarkthorne, looking good now! No crashes!

@vadi2 and @QwindorRousseau this one looks good to me now, should be good to merge.

**Review by vadi2 — APPROVED** [review]

**Comment by vadi2** [comment]
@QwindorRousseau how're you going with availability, would you like to review it?

**Pull request merged**
