### PR TITLE
Borgron Foray and GH Caves

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
NEW AREA - A partially crumbled fortress - Borgron Foray
Added Savannah greathunt cave
Redesigned great hunt cave area
Fixed some pathing in Delos
Reformatted Muurn Lake
Fixed a few shop names
Fixed a few wormholes

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]

**Comment by vadi2** [comment]
@QwindorRousseau able to review? It would be good to get this out to players fast

**Comment by QwindorRousseau** [comment]
Only thing that I really see wrong is that somewhere you have an errant wormhole. There should always be an even number of wormholes and there is an odd number of them currently. so either there is a wormhole somewhere that is not linked on both sides or there is a room with two wormholes in it.

**Review by QwindorRousseau — CHANGES_REQUESTED** [review]
Errant wormhole somewhere as said in comments.

**Comment by ryanstadther** [comment]
@QwindorRousseau looks like there are a bunch of wormholes in rooms in a NIL (-1) area....so not sure what those are...will get them fixed up and resubmit

**Comment by vadi2** [comment]
Okay but we've previously valued wormholes very little as they change all the time - can't reject a map after a week just for that. Nobody will want to map then. I'll put this through as the issue is minor and can be corrected in a follow-up.

**Pull request merged**
