### PR TITLE
Shopnames up to date everywhere. Wormholes updated. Added and changed a couple 'room marks'

### PR DESCRIPTION
**Pull request by PhoenixCodes**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes

Updated shop names everywhere
Cleaned up a lot of wormholes
Locked all wormholes
Added some rooms in Eleusis
Mapped Scion's Den at request
Adding/Updating some Room Marks (see below)
Flattened Mysia

## room mark changes
mysia - (removed) Reason: Flattening Mysia means no need for a Mysia mark
tasurke (added)- Reason: typing 'tasur'ke' is  honestly a PITA. There's a reason Achaea has Tasurke as a valid alternative in any place you'd be spelling it (walk to, help, etc)
newhope (changed): Bring in line with Walk To - nobody wants to go all the way into the village, they usually want to be close to harbour
new hope (added)- Reason: already have newhope, new hope for those of us who AREN'T lazy, too
ulangi (added): All of Ulangi is really one area; people don't want to have to select 'which ulangi did I mean' when they 'goto ulangi'. They meant get me to the island.
quisalis (added): Very dangerous/aggressive area. Better to prefer the room just below the gate regardless of where we are coming from (or what warp we are using)
delos (changed): Bring in line with new Walk To - old one was not in Delos area.

### CODE REVIEW

**Comment by ryanstadther** [comment]
should probably get the room marks added here too if we are changing them so everyone knows which ones are approved.

https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/wiki/PR-Checks

**Comment by QwindorRousseau** [comment]
When i get back home i can do the update and check. I got dragged from home for the evening.

**Comment by PhoenixCodes** [comment]
> should probably get the room marks added here too if we are changing them so everyone knows which ones are approved.

Yeah, planned on that. Wanted to get this reviewed and merged first!

**Comment by vadi2** [comment]
Can you add the json diff as well?

**Comment by PhoenixCodes** [comment]
> Can you add the json diff as well?

Unfamiliar with this, new procedure? Are there instructions on how to do this?

**Comment by vadi2** [comment]
Yeah, see https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/wiki/Updates and https://wiki.mudlet.org/w/IRE_mapping_script#map_save_-_save_the_map

**Comment by PhoenixCodes** [comment]
image
@vadi2 I'm unable to save a JSON for some reason, so no. I'm not sure if it's just the scope of the changes, the types of changes made, or something else going on here. We shouldn't require this until it works flawlessly.

**Comment by vadi2** [comment]
The export does work fine, don't worry - it just requires a name right now in 4.11, and won't in 4.12. The mapper's alias could use an improvement here.

So do `map save all shopnames` for example and you'll be good :+1:

**Comment by ryanstadther** [comment]
But for real, do ‘map save all map’ since the current file name is map :)

**Comment by PhoenixCodes** [comment]
Will  handle today/tonight!

**Comment by vadi2** [comment]
Could you re-upload both map and json with wormholes locked ([PR checks](https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/wiki/PR-Checks))? Looks good to me otherwise :+1:

**Comment by QwindorRousseau** [comment]
I will finish this up and do the corrections once i can wrap my head around all that has happened. Forgive me for a couple days.

**Comment by ryanstadther** [comment]
@QwindorRousseau and @vadi2, I looked this one over and there is one extra room mark called 'barracks' but I would recommend this PR just get approved and I can fix it in a future pull so we can get this one out and move on to @TheLastDarkthorne 's PR.

Everything else looked great so I think it is good to go!

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
