### PR TITLE
Hashan updates!

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Fixed planetarium and added the new fancy laboratory area! (special exits not included per request on security)

### CODE REVIEW

**Comment by ryanstadther** [comment]
does this include the other open PR? We have two PRs open now, but I don't think we can merge maps...

**Comment by TheLastDarkthorne** [comment]
Oh, I didn't realize it was being worked on lol oops

**Comment by TheLastDarkthorne** [comment]
I will close this and map the changes again later then, sorry!!

**Comment by ryanstadther** [comment]
No worries...that one has been open longer than typical too unfortunately.

**Comment by TheLastDarkthorne** [comment]
I'm reopening this cause I learned I could just take the updated JSON when the other PR is ready and put my changes in it and save the binary from it after! So I will do that whenever the other one is ready :)

**Comment by ryanstadther** [comment]
@TheLastDarkthorne hold up on this one actually for a bit, people are reporting crashes after that lastest update...might have to revert it.

**Comment by ryanstadther** [comment]
@TheLastDarkthorne the map has been reverted. You can attempt your merge now! Thanks!

**Comment by TheLastDarkthorne** [comment]
I don't have permission to merge, but feel free to test it and see if it goes well and merge if it does!

**Comment by vadi2** [comment]
It can't be merged - because more things have been merged since this PR was opened, the conflicts need to be resolved, see below. Remaking the PR would be the simplest way to solve them.

**Comment by ryanstadther** [comment]
@TheLastDarkthorne technically...we reverted back to the map version you were using prior to the recent crashing issue. So you should be able to just open a new PR and load your map as is... shouldn't need to do any fancy json map merging or anything like that.

**Pull request closed without merging**
