### PR TITLE
Added the Ziggurat of Malignancy

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes

Added new area, the Ziggurat of Malignancy in the Black Rock

### CODE REVIEW

**Comment by QwindorRousseau** [comment]
I will take a look and let you know if anything is wrong when I get off work tonight.

**Comment by ryanstadther** [comment]
@QwindorRousseau found two shops that changed names...added that quick as well.                                                        8536 in Cyrene and 5450 in Hashan.

**Comment by ryanstadther** [comment]
Added the additional room in Nimick too

**Comment by ryanstadther** [comment]
@QwindorRousseau I know you are likely super busy, but just checking in on this one. Let me know if there is anything you need me to change.

**Comment by QwindorRousseau** [comment]
I haven't forgotten about you. Just bad timing is all. Currently getting laid off and my computer setup is in pieces because I am doing a dual screen mount for my desk and I was missing a couple of tools to get it done right. I should be up and running to look at it tonight or tomorrow. Depends on how much of a pain getting these holes drilled for the bolts are.

**Pull request merged**
