### PR TITLE
Hesperia Estate fixed per request

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
Per request, also changed the layout of the Houses area so they don't get all cluttered together and confusing.

## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Hesperia Estate fixed
Houses area layout improved a bit so that they don't get all cluttered in the same space

### CODE REVIEW

**Comment by TheLastDarkthorne** [comment]
Omg I messed stuff, bear with me lol fixing it

**Comment by ryanstadther** [comment]
@TheLastDarkthorne looks like you just left Hesperia in the generic "Houses" area, did you not want it in its own area?

**Review by keneanung — COMMENTED** [review]
Are rooms 44, 76 and 61265 by design at the same location?

**Comment by TheLastDarkthorne** [comment]
Didn't see those rooms there lol I deleted them since they don't belong anywhere

**Comment by TheLastDarkthorne** [comment]
There's a lot of stray rooms in that area, I imagine due to other people trying to map their own houses and it somehow got into the live version? Idk. I didn't messed with them just moved them all away from this estate cause they can belong to other houses.

**Comment by keneanung** [comment]
I'm fine with this now. Just one thing I noticed when going through the JSON map: there are about 20 labels added (most likely from a people tracker like svof's). @ThaisenLV  @vadi2 do we want to keep them? I'd say we better don't... But then it's a similar issue as with profile locations (I forgot the name)

**Comment by ryanstadther** [comment]
Yeah the labels can be removed...but they don't hurt anything. I'll add it to my list of things to clean up in a future PR

**Comment by vadi2** [comment]
Agreed with @ThaisenLV.

**Comment by vadi2** [comment]
Let's merge this?

**Review by keneanung — APPROVED** [review]

**Pull request merged**
