### PR TITLE
Fixed Hesperia Estate per request

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
Put more rooms and fixed layout per request

## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [ ] Added changed map file
- [ ] Added changed JSON map file
- [ ] Used a descriptive pull request title
- [ ] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [ ] Added a short sentence summarizing the changes to the `changelog.txt` file
- [ ] Increased the number in `version.txt` by 1

### CODE REVIEW

**Comment by ryanstadther** [comment]
@keneanung looks like the danger checks failed :( But I can tell already we need a few more things. The JSON map, increment version and something in the changelog for sure @TheLastDarkthorne.

**Comment by vadi2** [comment]
If you can upload the map elsewhere, say we transfer, I can load it in here for you.

**Comment by ryanstadther** [comment]
@TheLastDarkthorne there are also a bunch of extra room marks that need to be removed. "j", "cata2", "annwyn2", "shop", "qboard", "pdock", "sead","nexit" among some of them, but it looks like a bunch more.

@keneanung assuming the danger check failed because of missing JSON map?

**Comment by TheLastDarkthorne** [comment]
> @TheLastDarkthorne there are also a bunch of extra room marks that need to be removed. "j", "cata2", "annwyn2", "shop", "qboard", "pdock", "sead","nexit" among some of them, but it looks like a bunch more.
> 
> @keneanung assuming the danger check failed because of missing JSON map?

Oops, I will work on that and upload new versions, sorry!

**Pull request closed without merging**
