### PR TITLE
// Elemental Embassy & most elemental planes

### PR DESCRIPTION
**Pull request by zylvyn**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below)
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes: Mapped: 
- the Coterie of Clouds
- The Elemental Embassy
- Garash's Grief (Minus the green section)
- the Vault
- Sllshya's Maw
- Ashen Blight
- Kkractle's Grasp

### CODE REVIEW

**Comment by QwindorRousseau** [comment]
I will take a look at it tomorrow when I wake up but i do have pending updates right now as well that i havent pushed because the layout isnt right yet

**Comment by zylvyn** [comment]
I've mapped Sllshya's Maw, the Vault, and a large chunk of Garash's Grief (Before the guards started to all team me), which I think would go in a different pull req. (given the specific scope of this one)

**Comment by vadi2** [comment]
Nice! Thanks for the contribution, would like to see this merged.

**Comment by QwindorRousseau** [comment]
The way the map works isnt lime script where it just does a change to the script. It overwrites the map with whatever the new map is and loses any changes someone else made.

**Comment by vadi2** [comment]
I know, but getting more people into doing the map updates is a good thing, and this person has submitted their update in before you were ready, I wouldn't want to see their work wasted.

btw there is a map merge script in Dropbox from years ago

**Comment by QwindorRousseau** [comment]
who are you in game. obviously not vadi

**Comment by zylvyn** [comment]
I wish I was more familiar with GitKraken to really grasp how all these pushes/pulls/etc's work.

I'm Ryldagh ICly.  And talking with you right now, Qwin.

**Comment by zylvyn** [comment]
@vadi2 Apparently the merge script doesn't work, and just breaks the map.
There isn't a way to export specific areas from the map file, and then import them into a different map, is there?

**Comment by QwindorRousseau** [comment]
We have talked and with the amount of stuff in my version that was a bit more difficult to get going to close this request without merging and then we will work on adding those areas together and getting something a bit better set up for communicating between mappers.

**Comment by vadi2** [comment]
Yes I'd like to see more mappers join the project.

**Comment by zylvyn** [comment]
@vadi2 Sorry I didn't reply in-game.  I was literally packing my laptop into the car to change locations.  I'm back on now.  What's up?

**Pull request closed without merging**
