### PR TITLE
Danger: Avoid unlocked wormholes

### LINKED ISSUE #80: New Danger Rule - Wormholes
New potential danger rule to ensure all wormholes are locked by default in the map.

### PR DESCRIPTION
**Pull request by keneanung**
Implemented the next danger rule: don't allow unlocked wormholes. Closes #80 

Also documented existing Rule classes and did some renamings.

### CODE REVIEW

**Review by vadi2 — COMMENTED** [review]
Lodash isn't in my toolbox of expertise so I'll let someone else review & test this one, I'm not able to follow the checking logic.

**Comment by keneanung** [comment]
`some` is basically `any` in C#/LINQ and `filter` is `where`... But I get that

**Review by vadi2 — APPROVED** [review]
Logic checks out

**Comment by keneanung** [comment]
I'll let it season a little for others to comtemplate.

**Pull request merged**
