### PR TITLE
More Flattening and Outdoor Tag

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
-Added new "Outdoor" tag to pretty much everywhere on Sapience and Meropis. Next priority will be islands.
-New area: Reckoning of Queen Titania
-Added missing room for Reckoning of Telaan
-Continued Flattening: Zaphar Isle, Bella's Keep, Tir, Petra, Harae, Dun Fortress, Piraeus, Minos, Sunderlands, Judgement Mountain

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]
Looks good. Can anyone test?

**Comment by ryanstadther** [comment]
One thing I just remembered is locking wormholes....let me verify they are all locked...and run through any other PR checks I forgot about! :)

**Comment by ryanstadther** [comment]
Also just got a request to do an update on some rooms in Ashtan. Gonna take a look tonight and see if I can get it sorted and added to the PR.

**Comment by ryanstadther** [comment]
Okay, found some stockrooms that I forgot to deleted, those are fixed up. Wormholes locked. Also fixed up all of the Bloodthroat Fortress changes by request from Grandue. Should be good to go!

**Comment by vadi2** [comment]
Let's get this tested and merge.

**Pull request merged**
