### PR TITLE
The massive rehaul of continents

### PR DESCRIPTION
**Pull request by QwindorRousseau**
Areas needed for wings update are:
main - normal wings
island - island wings
meropis - meropis wings

### CODE REVIEW

**Comment by keneanung** [comment]
@QwindorRousseau can you list the new continent names again and which travelling ability are allowed from that continent (including which rooms they lead to)?

**Comment by QwindorRousseau** [comment]
I can once I get off work and get home.

**Comment by QwindorRousseau** [comment]
Main continent
-duanathar: room 3885
-duanatharan : room 4882

Meropis continent
-duanathar: room 51188
-duanatharan: room 51603

Here is the complicated one. Island wings will work on several of the continent areas but it will take you to the same room regardless. The continents it will work on are: main, meropis, island, and north. There will need to be a new option added so that it can use the island wings as the activation word is different.

duanatharic: room 47571

I had also split up the northern area seeing as you can gare from the inner islands and the northern area where normal wings will not work so that we could hopefully add gare in there eventually and it would work on all the same areas as the island wings.

**Comment by QwindorRousseau** [comment]
Any update as to the status of getting this ready for release?

**Comment by keneanung** [comment]
I originally wanted to add all new wings and stuff in a single mapper update, but it looks like my time constraints prevent me from thinking too long about the "right" solution. I'll change the area identification for the main wings in a first PR, so things keep working and this PR can go through.

**Pull request merged**
