### PR TITLE
Updates and Alterations

### PR DESCRIPTION
**Pull request by SlyViolin**
Updates - All city shops, Baelgrim Fortress, West Ithmia, Suuthern Vashnars, Nur Circle 6, New Hope Disconnected - Sparrow's Rest, Aerithian Falls
Added - Cyrene Road

## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

### CODE REVIEW

**Comment by SlyViolin** [comment]
Wrong file. Let's try again with PASSION

**Comment by SlyViolin** [comment]
Actually, these are the right files and these areas a definitely unlocked.

**Comment by ryanstadther** [comment]
It doesn't show it properly when you look at 'area lock' in game...but they are definitely locked in the map.
image

image

image

image

I would suggest just going in and locking/unlocking those areas again and see if that works.

**Comment by keneanung** [comment]
Thanks for the changes :heart: 

Some feedback from me:
- Room `4263` has now 2 special exits to the same room, with one missing the `d` command. Could you delete the wrong one?
- Did Room `11920` loose its name by design?

**Comment by SlyViolin** [comment]
Dakhota, Azdun, Catacombs and Mannaseh unlocked in this version.
Room 4263 - I couldn't see the second special exit but a cleared all special exits and readded the correct one.
11920 is an exiting room but I don't have the door permissions to enter and populate the name etc.

**Review by keneanung — APPROVED** [review]
> Dakhota, Azdun, Catacombs and Mannaseh unlocked in this version.

Perfect, thanks!

> Room 4263 - I couldn't see the second special exit but a cleared all special exits and readded the correct one.

This might be due to the way the mapper identifies special exits. But at least the visual diff only show 1 now. What confuses me is that the same exit is already listed in the textual diff? Didn't it work before? I wonder if that's an error in the diff display thing...
image

> 11920 is an exiting room but I don't have the door permissions to enter and populate the name etc.

That's fine. I just noticed it and wanted to make sure there's a reason :slightly_smiling_face: 

Overall, this PR looks good to me!

**Review by vadi2 — APPROVED** [review]

**Comment by SlyViolin** [comment]
Might have something to do with the brackets in the special exits. On the second entry there is two open brackets instead of just one.

**Pull request merged**
