### PR TITLE
Updated Hashan's map

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Added new rooms in Hashan (Bathhouse in House of Delights, Hall of trinkets)
Updated some room names that got changed in Hashan's Citadel (Library)
Updated the names of some Hashan's shops.

### CODE REVIEW

**Review by QwindorRousseau — CHANGES_REQUESTED** [review]
In the map itself you need to run the --delete known stockrooms-- alias as there is one that got left in there as well as the room marks list needs to look like so

(mapper): Known marks in this map:
  ashtan                 436
  catacombs              36697
  cyrene                 6298
  delos                  1180
  dun                    3886
  eleusis                6738
  excrucio               8121
  flame                  2898
  genji                  10095
  grukai                 27931
  hashan                 4472
  inbhir                 10913
  invidia                8162
  ioje                   52029
  istarion               22385
  judgement              35548
  kamleikan              9578
  kunapi                 52123
  kuthalebak             51850
  letum                  8489
  lhitsu                 52391
  loramere               52516
  meropis                1226
  mhaldor                11400
  moghedu                6
  mourning               37797
  myrinia                52554
  mysia                  9869
  newhope                24310
  not                    1299
  prialysh               50884
  qboard                 23900
  qerstead               52298
  quaskan                50832
  radak                  45519
  revenant               7211
  riagath                30234
  rip                    3415
  sirocco                30152
  taryen                 21767
  thera                  20386
  tir                    1102
  tree                   2898
  ur                     50935
  uw                     14594
  wegava                 33127
  yggdrasil              54133

**Comment by TheLastDarkthorne** [comment]
Ok. I fixed the stockroom issue, I don't know about the mark list though, I haven't touched any other area aside of Hashan, and my marks list have way more items listed than the list that you posted in the comment though, but the numbers seem to be okay at least for the areas in your list.

(mapper): Known marks in this map:
  aexit                  17347
  agdock                 30222
  agpshrine              27899
  agshrine               31059
  annwyn                 4840
  annwyn2                3215
  aran                   7584
  archon                 4387
  arcshrine              15954
  arshrine               19782
  ashtan                 436
  atrocitas              8540
  bank                   3761
  barakus                45918
  barracks               4389
  bloodpear              5086
  casov                  20873
  cata2                  29074
  catacombs              36697
  cauldron               487
  chighway               30308
  cm                     455
  coterie                45029
  cyrene                 6298
  delos                  1180
  dockhand               531
  dojo                   6612
  dshrine                3938
  dummy                  7216
  dun                    3886
  dunshrine              3938
  ecalith                23770
  eleusis                6738
  embassy                45076
  emq                    446
  excrucio               8121
  flame                  2898
  fshrine                32724
  gates                  436
  genipede               54084
  genji                  10095
  grotto                 38174
  grukai                 27931
  hashan                 4472
  highway                23747
  house                  502
  icon                   3372
  imark                  29668
  inbhir                 10913
  invidia                8162
  ioje                   52029
  ishrine                30121
  istarion               22385
  judgement              35548
  kamleikan              9578
  kunapi                 52123
  kuthalebak             51850
  lab                    38229
  letum                  8489
  lhitsu                 52391
  loramere               52516
  manarashrine           19086
  meropis                1226
  mhaldor                11400
  mog                    328
  moghedu                6
  mourning               37797
  mshrine                19086
  myrinia                52554
  mysia                  9869
  newhope                25864
  nexit                  26329
  nish                   27755
  nishportal             26329
  not                    1299
  nshrine                27755
  oicon                  22471
  pdock                  33595
  pharbour               33595
  prialysh               50884
  pshrine                21567
  qboard                 23900
  qerstead               52298
  qshrine                28035
  quaskan                50832
  radak                  45519
  rageteeth              1226
  revenant               7211
  riagath                30234
  rip                    3415
  seat                   29699
  shop                   5392
  sirocco                30152
  ssicon                 23382
  taryen                 21767
  tasur                  28627
  telward                16297
  thera                  20386
  tir                    1102
  tree                   2898
  treeshrine             15159
  trueicon               23251
  tshrine                37774
  tuarshrine             19365
  underrealm             50935
  underworld             14488
  ur                     50935
  ushrine                34985
  uw                     14594
  wegava                 33127
  wlicon                 21732
  yggdrasil              54133
  zdock                  31215
  zshrine                26900

**Comment by PhoenixCodes** [comment]
I'd like to request a day delay on this PR for further verifications, I'll get back to you by this time tomorrow. Ignore if this is out of line.

**Comment by vadi2** [comment]
Sure, feel free to review it!

**Comment by QwindorRousseau** [comment]
Still needs to have all those extra room marks deleted for the upload file.

**Comment by PhoenixCodes** [comment]
Short the above, I see no issues with it. What are all those extra marks from?

**Comment by QwindorRousseau** [comment]
@PhoenixCodes https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/wiki/PR-Checks

**Comment by TheLastDarkthorne** [comment]
Ok fixed the marks. They seem to be alright now, tell me if there is anything else
And sorry for the mess :(

**Comment by vadi2** [comment]
No problem at all.

Everyone else good with it?

**Comment by QwindorRousseau** [comment]
You deleted out yggdrasil but otherwise the rest of the extra ones are gone.

**Comment by ryanstadther** [comment]
@QwindorRousseau I have a question on this one, is there a specific reason we use room marks and not room features?

**Comment by vadi2** [comment]
I think because room features got added to the script much later than room marks - the achaean crowdmap predates features. It would be a good idea to investigate if it's worthwhile to switch!

**Comment by QwindorRousseau** [comment]
I will have to look into the features again but yes it predated that so nothing was really converted over or if I had looked into it I do not remember why I didn't convert it over.

**Comment by ryanstadther** [comment]
Ok, after a little testing it looks like it is more suited for things like wilderness exits, then you can just do GOTO WILDERNESS and it will take you to the nearest one. Still neat for just that use case alone! :) But for set landmarks, marks might be better. Thanks @QwindorRousseau and @vadi2.

I might throw out a PR in the future adding all wilderness exits as a feature. I think that would be pretty neat.

**Comment by PhoenixCodes** [comment]
If it's useful for that, we should update shops, wilderness exits, postal,
bank, harbour, and subdivision entrances to use these features. Ryan, can
you share what tests you did with them and what modifications we might need
to make to the mapper script to account for using them instead of room
characters? Or maybe we'd use them with room characters.

Roland Goldberg
479-653-3893
----

**Comment by ryanstadther** [comment]
@PhoenixCodes So, it looks like you can attach a room character to a 'feature', so whenever a room is marked with that feature the character is automatically added.

Features are created using FEATURE CREATE (e.g. feature create wilderness char W), this would create a wilderness feature and assign the character W. Then you can go around and do RCF WILDERNESS wherever and it will attach the feature and the character.

Once all the rooms are tagged you can do GOTO FEATURE WILDERNESS and you would autowalk to the closest wilderness exit.

Rooms can be tagged with multiple features, so you could have a harbour and a wilderness room for example. I totally agree, we could basically convert anything that is just a simple character now over to a feature, it is a pretty slick "feature" :)

There is a feature migrate function to take existing character marks and convert them to features, it seems like it wouldn't be too difficult actually.

It would be nice though if there was a function in the mapper script to list out features by room id, just like "show char marks", but not critical.

**Comment by TheLastDarkthorne** [comment]
Ok I put the yggdrasil mark back

**Comment by QwindorRousseau** [comment]
Everything is good now. Thanks.

**Review by QwindorRousseau — APPROVED** [review]
All good now.

**Pull request merged**
