### PR TITLE
Migrated room MARKS to room FEATURES

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Converted nearly all room marks into features to enable the GOTO FEATURE functionality, current features are subdivision, ferry, commodityshop, locksmith, stronghold, shop, news, harbour, wilderness, arena postoffice, bank.

All room marks should be added as features (which also adds the mark) going forward.

### CODE REVIEW

**Comment by ryanstadther** [comment]
Added another change to pull request. A gate in Eleusis was changed from a special exit ('push gate') to simply a normal exit.

**Comment by vadi2** [comment]
Sorry for the delay, it looks like @QwindorRousseau is busy so I'll have a look at this.

Are marks still present, or did they get deleted? That is, after people update to this map - will everything "just work" still?

**Comment by ryanstadther** [comment]
hey @vadi2, no worries. Marks are still present. Each "feature" is tied to a room mark, so when you add the feature it automatically adds the mark as well. Everything is the same except now people will be able to use the GOTO FEATURE WILDERNESS command (or harbour, commodityshop, stronghold, etc)

**Comment by vadi2** [comment]
That sounds great. @QwindorRousseau mentioned he'll be able to look at this soon, and otherwise I'll test it out and merge.

**Comment by ryanstadther** [comment]
just uploaded a new map file, fixed a wilderness feature and modified layout of Kunapi to align better with IG map

**Review by vadi2 — APPROVED** [review]
Looks good, thanks a lot and sorry for the delay.

**Pull request merged**
