### PR TITLE
Continent Fixes

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
A lot of continents were messed up (probably due to the fact I didn't realize they were a thing until recently!), so I did a mass cleanup on those. Should help utilize wings better in a few spots (and not even attempt wings in a few others where it shouldn't)
Flattened layout of Lothos and a small section of Dun Valley
Fixed up shop names (Everywhere but Eleusis)
Cleaned up Room Marks to align with new Danger Rule

### CODE REVIEW

**Comment by ryanstadther** [comment]
@keneanung looks like the map diffs didn't work?

**Comment by ryanstadther** [comment]
I also threw in a minified json file for the Nexus map package... I'm fine doing it manually for a while until/if something gets automated for it.

**Comment by ryanstadther** [comment]
@keneanung and @vadi2 ...those danger checks are freaking awesome IMO :) Thanks!!

**Comment by keneanung** [comment]
> @keneanung looks like the map diffs didn't work?

See #95 for a fix to that.

**Comment by ryanstadther** [comment]
Awesome, once that one is pushed I'll resubmit this one to see how the diffs look.

**Comment by keneanung** [comment]
No need to re-submit. I'll just push an empty commit so the action is re-run

**Comment by keneanung** [comment]
There's the diff. But room `13275` confuses me... It has no exits.

Edit to add: it exists on the old map as well.

**Comment by ryanstadther** [comment]
It is a stockroom, so it is disconnected from the map when you do the deletedknownstockrooms. I don't think the rooms are ever actually deleted?

**Comment by ryanstadther** [comment]
Also...it is a lot...but it is pretty great...can basically do entire review from the PR now. Awesome stuff!

**Comment by keneanung** [comment]
> It is a stockroom, so it is disconnected from the map when you do the deletedknownstockrooms. I don't think the rooms are ever actually deleted?

Huh, you're right... I thought the rooms were deleted. Disregard then

**Review by keneanung — APPROVED** [review]
The changes look good. I especially like the custom exit lines that connect the in/out and up/down rooms.

**Comment by ryanstadther** [comment]
@keneanung and @vadi2 Eleusis unlocked for real this time! Also added the new Logosmas area! :)

**Review by keneanung — APPROVED** [review]
Looks reasonable to me!

**Comment by vadi2** [comment]
I can't make sense of this diff... but that's no different than before we had all the pictures. Go ahead I say.

**Pull request merged**
