### PR TITLE
LHG Mapping

### PR DESCRIPTION
**Pull request by SlyViolin**
- Mapping of new Lupine Hunting Grounds.
- Room mark : LHG @ 5007 'Altar of the Hunt' (Northreach) to replicate previous room mark before LHG was shut off.
- First time mapper. Critics super welcome!
(mapper): version 21.12.3

## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Added changed JSON map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

### CODE REVIEW

**Comment by ryanstadther** [comment]
Is room 108 legit or no? It is kind of on its own.

Is room 45286 a player house? should be moved to the "houses" area.

Otherwise this looks great! IMO this can be approved without fixing 45286 since other people are in the queue to do some mapping...it can be fixed in the future if it is a player house.

**Comment by ryanstadther** [comment]
@keneanung is is possible to put all the mapdiffs in a spoiler tag or something like that? It is kind of tricky to see when each diff starts and ends when there are multiple mapdiff comments like in this one. :)

**Comment by keneanung** [comment]
> @keneanung is is possible to put all the mapdiffs in a spoiler tag or something like that? It is kind of tricky to see when each diff starts and ends when there are multiple mapdiff comments like in this one. :)

I thought they did already, but... looks like I overlooked the default settings

**Comment by keneanung** [comment]
I have found some new room characters which may not be desired:
- 7522, 4992, 4996, 5005, 7522, 11807, 11830, 11900, 17482: "A"
- 10736: "1"
- 10758: "2"
- 10738: "3"
- 10739: "4"
- 11784: "5"
- 11785: "6"
- 11786: "7"

**Review by keneanung — APPROVED** [review]
Looks good to me. Thank you so much for pushing through :partying_face: @ThaisenLV what do you think?

**Pull request merged**
