### PR TITLE
Updated Unnamed Fortress

### PR DESCRIPTION
**Pull request by grandue1986**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]
Looks good to me. Let's have @ThaisenLV and @keneanung double-check it too!

**Comment by ryanstadther** [comment]
It looks like there are a bunch of new wilderness rooms...are those actually connecting anything or was the mapper left on while walking through?

Other than that it looks great!

**Review by keneanung — COMMENTED** [review]
I agree with ThaisenLV here. I'd be happy if the wilderness rooms weren't there.

**Comment by vadi2** [comment]
How can we remove them without redoing the mapping work?

**Comment by vadi2** [comment]
@ThaisenLV @keneanung mind reviewing?

**Comment by ryanstadther** [comment]
GitHub is still showing the wilderness rooms, I can check it manually later today though.

**Comment by vadi2** [comment]
@ThaisenLV good now?

**Comment by ryanstadther** [comment]
looks good to me!

**Comment by vadi2** [comment]
Nice. Will merge tomorrow if there's no issues found.

**Comment by vadi2** [comment]
Thanks a lot for your work on this @grandue1986 @ThaisenLV @keneanung ! The online diffs helped catch an unintended change, that was quite useful :)

**Pull request merged**
