### PR TITLE
Added Balan'maal and Balan'ukia

### PR DESCRIPTION
**Pull request by TheLastDarkthorne**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Added two areas (Balan'maal and Balan'ukia)
Fixed some rooms (see commit description)

### CODE REVIEW

**Comment by TheLastDarkthorne** [comment]
Ignore that merge I don't know how to delete it... it is not needed. I'm kinda new to GitHub... Anyway!

**Comment by QwindorRousseau** [comment]
If you are not already please join the discord.

**Comment by vadi2** [comment]
@QwindorRousseau is this good to go?

**Comment by QwindorRousseau** [comment]
@vadi2 Almost. Working with them right now for the last couple of edits and then it will be.

**Pull request merged**
