### PR TITLE
Try a weird map to check new map diffs

### PR DESCRIPTION
**Pull request by vadi2**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [ ] Added changed map file
- [ ] Added changed JSON map file
- [ ] Used a descriptive pull request title
- [ ] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [ ] Added a short sentence summarizing the changes to the `changelog.txt` file
- [ ] Increased the number in `version.txt` by 1

## Included changes
How the map looks like in Mudlet:

image

### CODE REVIEW

**Comment by keneanung** [comment]
Uh, I forgot... You need to explicitly check out the head/merge commit in the checkout action. See the danger run for comparison

**Comment by Delwing** [comment]
Yep, I need to address that
 This is my next item.

**Comment by vadi2** [comment]
Works great!

**Comment by ryanstadther** [comment]
@vadi2 and @keneanung is it going to show every single room change? If so...that could get unreasonably long for certain PRs.

**Comment by keneanung** [comment]
That's the current feature set, yeah. Let's have a look how it turns out, then give feedback

**Comment by vadi2** [comment]
@delwing

**Comment by Delwing** [comment]
Not sure at the moment. PRs welcome though

**Pull request closed without merging**
