### PR TITLE
Cyrene River and Graveyard

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x ] Added changed map file
- [x ] Used a descriptive pull request title
- [x ] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x ] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x ] Increased the number in `version.txt` by 1

## Included changes

Updated Cyrene river with new bridges and added new Cyrene graveyard area near pantheon

### CODE REVIEW

**Comment by ryanstadther** [comment]
Question: If a pull request is accepted does an Admin remove the lock in the Wiki or are we responsible for that?

**Comment by vadi2** [comment]
You would take it off.

I'll let @QwindorRousseau test and accept these map changes. Thanks for getting doing them! :grin:

**Comment by QwindorRousseau** [comment]
If you could just add in at the bottom of the main pull request the details of what you added that would be awesome.

**Comment by ryanstadther** [comment]
Updated included changes section. I think that was what you were referring to?

**Review by QwindorRousseau — APPROVED** [review]

**Pull request merged**
