### PR TITLE
Fixed Cyrene Baths and Caverns of Chiada

### PR DESCRIPTION
**Pull request by ryanstadther**
## Checklist

The list below serves as a reminder to make sure, all needed changes were added to the repository. You can add a `x` between the square brackets to tick the items when in edit mode or just tick the checkboxes when not.

If you forgot something, don't worry. Just do the changes on the same branches and they are added automatically to the pull request.

- [x] Added changed map file
- [x] Used a descriptive pull request title
- [x] Wrote a short description of the change in the pull request description (see below). Include area names where possible.
- [x] Added a short sentence summarizing the changes to the `changelog.txt` file
- [x] Increased the number in `version.txt` by 1

## Included changes
Fixed Cyrene Baths
Condensed Imperium to align with IG map
Added Custom Exit Lines for weird exits in Caverns of Chiada
Moved a few Great Hunt Caves to Great Hunt Cave Area

### CODE REVIEW

**Comment by ryanstadther** [comment]
uploaded new map - fixed a bunch of Cyrene Shop names...gonna run through other cities quick too

**Comment by ryanstadther** [comment]
fixed shops in every city...a few in each

**Comment by ryanstadther** [comment]
forgot to wipe out the stockrooms...fixed that!

**Comment by QwindorRousseau** [comment]
need to delete the room mark H. must have gotten put in there when i wasnt able to check the last update due to internet going out for almost a week

**Comment by ryanstadther** [comment]
What do you mean? H is for Harbour.

**Comment by ryanstadther** [comment]
removed H room mark

**Pull request merged**
